---

history:
  1: Initial version.
  2: Minor bug fixes.
  3: Updates to Light style.
  4: Fixes an issue with social icons not displaying properly.
  5: Added more Design Editor options for text elements.

hidden: true
version: 5
api_version: 2
support:
  # feature_name: min version supporting it
  external_link_target_control: 1
  content_pages: 1
  grouped_vars: 1
  blog: 1
  responsive: 1
  client_access: 1
  sales: 1
  parent_page: 1
  base_vars: 1

can_automatically_upgrade_to_versions: [1, 2, 3, 4, 5]
