---
name: Spruce
description: Format theme

skins:
- name: Light
  id: light
  path: skin_images/light.jpg
- name: Dark
  id: dark
  path: skin_images/dark.jpg
- name: Grove
  id: grove
  path: skin_images/grove.jpg
default_skin: light

using_position:
  right: 20
  bottom: 20

preview_images:
- path: preview_images/1.jpg

mobile_preview_images:
  - path: preview_images/1-mobile.jpg

preview_site_images:
- preview_site_images/

filter_attributes:
- vertical
- tiled
