---
name: Spruce
description: Format theme

skins:
- name: Light
  id: light
- name: Dark
  id: dark
- name: Colored
  id: colored
default_skin: light

using_position:
  right: 20
  bottom: 20

preview_images:
- path: preview_images/1.jpg

mobile_preview_images:
  - path: preview_images/1-mobile.jpg

preview_site_images:
- preview_site_images/

filter_attributes:
- vertical
