---
name: blunt
description: Format theme
skins:
- name: Light
  id: light
- name: Dark
  id: dark
- name: Coloured
  id: coloured
default_skin: light
using_position:
  right: 20
  bottom: 20
preview_images:
- path: preview_images/1.jpg
background_images:
- path: background_images/1.jpg
preview_site_images:
- preview_site_images/
filter_attributes:
- vertical
